### ISSUE TITLE
The basic example is throwing an error right now

### ISSUE THREAD

**Issue by john-guerra** [ivelascog/TimeSearcherPlus#31]
```Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'at')
    at BVH.js:41:52
    at Array.forEach (<anonymous>)
    at pupulateBVHPolylines (BVH.js:25:10)
    at makeBVH (BVH.js:131:7)
    at BVH (BVH.js:20:13)
    at brushInteraction (BrushInteraction.js:70:10)
    at init (TimeSearcher.js:734:15)
    at TimeSearcher.ts.data (TimeSearcher.js:1667:9)
    at TimeSearcher (TimeSearcher.js:1708:8)
    at example/:29:18
(anonymous) @ BVH.js:41
pupulateBVHPolylines @ BVH.js:25
makeBVH @ BVH.js:131
BVH @ BVH.js:20
brushInteraction @ BrushInteraction.js:70
init @ TimeSearcher.js:734
TimeSearcher.ts.data @ TimeSearcher.js:1667
TimeSearcher @ TimeSearcher.js:1708
(anonymous) @ example/:29
Promise.then (async)
(anonymous) @ example/:22```

Please review @ivelascog

**Comment by john-guerra** [comment]
Fixed with the latest update
